cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name="add_cart"),
    path('',views.cart_detail,name="cart_detail"),
    path('remove/<int:product_id>/',views.remove_cart,name="remove_cart"),
    path('delete/<int:product_id>/',views.full_remove,name="full_remove"),
    path('checkout/',views.checkout,name="checkout"),

]

ecomapp/urls.py
from django.urls import path
from . import views

app_name='ecomapp'
urlpatterns=[
    path('',views.home,name='home'),
    path('all',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.Prodcatdetail,name='Prodcatdetail'),
    path('contact',views.contact,name='contact'),
    path('about',views.about,name='about'),
    path('signin',views.signin,name='signin'),
    path('signup',views.signup,name='signup'),
    path('forgot',views.forgot,name='forgot'),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from ecomapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include("cart.urls")),
    path('',include('ecomapp.urls')),
    path('search/',include('search_app.urls')),
    

]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns=[
    path('',views.searchresult,name='searchresult'),

]

cart/models.py
from django.db import models
from ecomapp.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    
    def __str__(self):
        return self.cart_id
    
class Cartitem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    
    class Meta:
        db_table='Cartitem'

    def sub_total(self):
        return self.product.price*self.quantity
    
    def __str__(self):
        return self.product

ecomapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse("ecomapp:products_by_category",args=[self.slug])
    def __str__(self):
        return '{}' .format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='product',blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'
    def get_url(self):
        return reverse("ecomapp:Prodcatdetail",args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}' .format(self.name)

search_app/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecomapp.models import Product
from .models import Cart,Cartitem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart
def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = Cartitem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except Cartitem.DoesNotExist:
        cart_item = Cartitem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')

def remove_cart(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = Cartitem.objects.get(cart=cart, product=product)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else :
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = Cartitem.objects.filter(cart=cart, product=product)
    cart_item.delete()
    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = Cartitem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price*cart_item.quantity)
            counter+=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))

def checkout(request, total=0,):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = Cartitem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price*cart_item.quantity)
    except ObjectDoesNotExist:
        pass
    return render(request, "checkout.html",dict(total=total))

ecomapp/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage



# Create your views here.
def home(request):
    return render(request,'index.html')

def contact(request):
    return render(request,'contact.html')

def about(request):
    return render(request,'about.html')

def signin(request):
    return render(request,'signin.html')

def signup(request):
    return render(request,'signup.html')

def forgot(request):
    return render(request,'forgot.html')

def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    products=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'category':c_page,'products':products})

def Prodcatdetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

search_app/views.py
from django.shortcuts import render
from ecomapp.models import Product
from django.db.models import Q
# Create your views here.



def searchresult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
        return render(request,"search.html",{'query':query,'products':products})

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Welcome to Cart
{% endblock %}
{% block title %}
  Cart---Shop Your Favourite!!!
{% endblock %}
{% block content %}

<section class="page-header">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="content">
					<h1 class="page-name">Cart</h1>
					<ol class="breadcrumb">
						<li><a href="{% url 'ecomapp:home' %}">Home</a></li>
						<li class="active">cart</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</section>
{% if not cart_items %}

<div class="">
    <div class="text-center">
        <br>
        <h1 class="text-center">Your Shopping cart is empty</h1>
        <br>
        <p class="text-center">
            Please click <a href="{% url 'ecomapp:allProdCat' %}">Here</a>
        </p>
    </div>
</div>
{% else %}
<div class="page-wrapper">
  <div class="cart shopping">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="block">
            <div class="product-list">
              <form method="post">
                <table class="table">
                  <thead>
                    <tr>
                      <th class="">Product ID</th>
                      <th class="">Item Name</th>
                      <th class="">Item Price</th>
                      <th class="">Quantity</th>
                      <th class="">Actions</th>
                      <th class="">Sub-total</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for cart_item in cart_items %}
                    <tr class="">
                      <td class="">{{cart_item.product.id}}</td>
                      <td class="">
                        <div class="product-info">
                          <a href="cart_item.product.get_absolute_url"><img width="80" src="{{cart_item.product.image.url}}"></a>
                          <a href="cart_item.product.get_absolute_url">{{cart_item.product.name}}</a>
                        </div>
                      </td>
                      <td class="">₹ {{cart_item.product.price}}</td>
                      <td class="">{{cart_item.quantity}}</td>
                      {% if cart_item.quantity < cart_item.product.stock %}
                      <td>
                        &nbsp; <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="my_a"><i class="bi bi-plus-lg custom_icon"></i></a>&nbsp;
                        <a href="{% url 'cart:remove_cart' cart_item.product.id %}" class="my_a"><i class="bi bi-dash-lg custom_icon"></i></a>&nbsp; 
                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class=""><i class="bi bi-trash3 custom_icon"></i></a>
                      </td>
                      {% else %}
                      <td>
                        &nbsp;<a href="{% url 'cart:remove_cart' cart_item.product.id %}" class="my_a"><i class="bi bi-dash-lg custom_icon"></i></a>&nbsp;
                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class=""><i class="bi bi-trash3 custom_icon"></i></a>
                      </td>
                      {% endif %}
                      <td>₹ {{cart_item.sub_total}}</td>
                      </tr>
                      {% endfor %}
                  </tbody>
                </table>
                <div class="pull-right che_out">
                  <p class="text-center">Your total is <strong>₹ {{total}}</strong></p>
                  <a href="{% url 'cart:checkout' %}" class="btn btn-main">Checkout</a>
                  <a href="{% url 'ecomapp:allProdCat' %}" class="btn btn-main">Continue Shopping...</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
        {{ category.desc |truncatewords:155 }}
    {% else %}
        welcome to cart store where you can buy.
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}-Shop cart
    {% else %}
        see our collections -Shop Cart
    {% endif %}
{% endblock %}
{% block content %}
<div>
	

	<section class="page-header">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="content">
						<h1 class="page-name">Shop</h1>
						<ol class="breadcrumb">
							<li><a href="{% url 'ecomapp:home' %}">Home</a></li>
							{% if category %}
                            <li class="" href="{% url 'ecomapp:allProdCat' %}">shop</li>
                            <li class="active">{{category.name}}</li>
                            {% else %}
                            <li class="active">shop</li>
                            {% endif %}
						</ol>
					</div>
				</div>
			</div>
		</div>
	</section>

	<div>
		<div class="title text-center">
    	{% if category %}

        	<h1>{{category.name}}</h1>
        	<p>{{category.desc}}</p>
		</div>
    	{% else %}
		<div class="title text-center">
        	<h1>Shop - Product Collection</h1>
		</div>
    	{% endif %}
	</div>

	<section class="products section">
		<div class="container">
			<div class="row">
				{% for product in products.object_list %}
				<div class="col-md-4">
					<div class="product-item">
						<div class="product-thumb">
							<span class="bage">Sale</span>
							<img class="img-responsive" src="{% static 'images/shop/products/product-5.jpg' %}" alt="{{product.name}}" />
							<div class="preview-meta">
								<ul>
									<li>
										<span  data-toggle="modal" data-target="#product-modal">
											<i class="tf-ion-ios-search-strong"></i>
										</span>
									</li>
									<li>
										<a href="#!" ><i class="tf-ion-ios-heart"></i></a>
									</li>
									<li>
										<a href="{% url 'cart:add_cart' product.id %}"><i class="tf-ion-android-cart"></i></a>
									</li>
								</ul>
							</div>
						</div>
						<div class="product-content">
							<h4><a href="{{product.get_url}}">{{product.name}}</a></h4>
							<p class="price">₹ {{ product.price }}</p>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
		<div class="text-center">
			{% for pg in products.paginator.page_range %}
			<a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
			{% endfor %}
		</div>
	</section>
</div>
{% endblock %}

templates/footer.html
<footer class="footer section text-center">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="social-media">
					<li>
						<a href="https://www.facebook.com/themefisher">
							<i class="tf-ion-social-facebook"></i>
						</a>
					</li>
					<li>
						<a href="https://www.instagram.com/themefisher">
							<i class="tf-ion-social-instagram"></i>
						</a>
					</li>
					<li>
						<a href="https://www.twitter.com/themefisher">
							<i class="tf-ion-social-twitter"></i>
						</a>
					</li>
					<li>
						<a href="https://www.pinterest.com/themefisher/">
							<i class="tf-ion-social-pinterest"></i>
						</a>
					</li>
				</ul>
				<ul class="footer-menu text-uppercase">
					<li>
						<a href="{% url 'ecomapp:contact' %}">CONTACT</a>
					</li>
					<li>
						<a href="{% url 'ecomapp:allProdCat' %}">SHOP</a>
					</li>
					<li>
						<a href="{% url 'ecomapp:about' %}">About Us</a>
					</li>
				</ul>
				<p class="copyright-text">Copyright &copy;2023, Developed by Akhil Roy</p>
			</div>
		</div>
	</div>
</footer>

templates/forgot.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="forget-password-page account">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="block text-center">
            <a class="logo" href="{% url 'ecomapp:home' %}">
              <img src="{% static 'images/logo.png' %}" alt="">
            </a>
            <h2 class="text-center">Welcome Back</h2>
            <form class="text-left clearfix">
              <p>Please enter the email address for your account. A verification code will be sent to you. Once you have received the verification code, you will be able to choose a new password for your account.</p>
              <div class="form-group">
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Account email address">
              </div>
              <div class="text-center">
                <button type="submit" class="btn btn-main text-center">Request password reset</button>
              </div>
            </form>
            <p class="mt-20"><a href="{% url 'ecomapp:signin' %}">Back to log in</a></p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/header.html
{% load static %}

<!-- Start Top Header Bar -->
<section class="top-header">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-xs-12 col-sm-4">
				<div class="contact-number">
					<i class="tf-ion-ios-telephone"></i>
					<span>0129- 12323-123123</span>
				</div>
			</div>
			<div class="col-md-4 col-xs-12 col-sm-4">
				<!-- Site Logo -->
				<div class="logo text-center">
					<a href="{% url 'ecomapp:home' %}">
						<!-- replace logo here -->
						    <svg width="135px" height="29px" viewBox="0 0 155 29" version="1.1" xmlns="http://www.w3.org/2000/svg"
							xmlns:xlink="http://www.w3.org/1999/xlink">
							<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" font-size="40"
								font-family="AustinBold, Austin" font-weight="bold">
								<g id="Group" transform="translate(-108.000000, -297.000000)" fill="#000000">
									<text id="AVIATO">
										<tspan x="108" y="328">SHOP</tspan>
									</text>
								</g>
							</g>
						</svg>                                                  
					</a>
				</div>
			</div>
			<div class="col-md-4 col-xs-12 col-sm-4">
				<!-- Cart -->
				<ul class="top-menu text-right list-inline">
					<!-- Search -->
					<li class="dropdown search dropdown-slide">
						<a href="#!" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"><i
								class="tf-ion-ios-search-strong"></i> Search</a>
						<ul class="dropdown-menu search-dropdown">
							<li>
								<form role="search" action="{% url 'search_app:searchresult' %}" method="get"><input type="search" class="form-control" placeholder="Search..." name="q"></form>
							</li>
						</ul>
					</li><!-- / Search -->

					<!-- Languages -->
					<li class="commonSelect">
						<select class="form-control">
							<option>EN</option>
							<option>DE</option>
							<option>FR</option>
							<option>ES</option>
						</select>
					</li><!-- / Languages -->

				</ul><!-- / .nav .navbar-nav .navbar-right -->
			</div>
		</div>
	</div>
</section><!-- End Top Header Bar -->

templates/nav.html
<!-- <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto me-auto mb-2 mb-lg-0">
         <li class="nav-item dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                Shop
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'ecomapp:allProdCat' %}">All Products</a></li>
                {% for cat in links %}
                    <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                {% endfor %}
            </ul>
            {% if item_count > 0 %}
            <li class="nav-item mr-auto">
                <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="tf-ion-android-cart"></i>{{item_count}}</a>
            </li>
            {% else %}
            <li class="nav-item mr-auto">
                <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="tf-ion-android-cart"></i></a>
             </li>
            {% endif %}
         </li>
        </ul>

      </div>
    </div>
  </nav> -->


  {% load static %}
<!-- Main Menu Section -->
<section class="menu">
	<nav class="navbar navigation">
		<div class="container">
			<div class="navbar-header">
				<h2 class="menu-title">Main Menu</h2>
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
					aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

			</div><!-- / .navbar-header -->

			<!-- Navbar Links -->
			<div id="navbar" class="navbar-collapse collapse text-center">
				<ul class="nav navbar-nav">

					<!-- Home -->
					<li class="dropdown ">
						<a href="{% url 'ecomapp:home' %}">Home</a>
					</li><!-- / Home -->

                    <li class="dropdown ">
						<a href="{% url 'ecomapp:about' %}">About Us</a>
					</li>
                    <li class="dropdown dropdown-slide">
						<a href="#!" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="350"
							role="button" aria-haspopup="true" aria-expanded="false">Shop <span
								class="tf-ion-ios-arrow-down"></span></a>
						<div class="dropdown-menu">
							<div class="row">

								<!-- Basic -->
								<div class="col-lg-12 col-md-12 mb-sm-6">
									<ul>
										<li class="dropdown-header">Categories</li>
										<li role="separator" class="divider"></li>
										<li><a href="{% url 'ecomapp:allProdCat' %}">All</a></li>
                                        {% for cat in links %}
										<li><a href="{{cat.get_url}}">{{cat.name}}</a></li>
                                        {% endfor %}

									</ul>
								</div>

							</div><!-- / .row -->
						</div><!-- / .dropdown-menu -->
					</li>
                    <li class="dropdown ">
						<a href="{% url 'ecomapp:contact' %}">Contact</a>
					</li>
                    <li class="dropdown ">
						<a href="{% url 'ecomapp:signin' %}">Sign-In</a>
					</li>
                    <li class="dropdown ">
						<a href="{% url 'ecomapp:signup' %}">Sign-Up</a>
					</li>
					{% if item_count > 0 %}
            		<li class="dropdown">
                    	<a href="{% url 'cart:cart_detail' %}"><i class="tf-ion-android-cart cart_nav" style="font-size:20px;"></i>{{item_count}}</a>
             		</li>
            		{% else %}
            		<li class="dropdown">
                		<a href="{% url 'cart:cart_detail' %}"><i class="tf-ion-android-cart cart_nav" style="font-size:20px;"></i></a>
             		</li>
            		{% endif %}
				</ul><!-- / .nav .navbar-nav -->

			</div>
			<!--/.navbar-collapse -->

		</div><!-- / .container -->
	</nav>
</section>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc|truncatewords:155}}
{% endblock %}
{% block title %}
  {{product.name}}--Shop Cart
{% endblock %}
{% block content %}
<div>
    <p class="text-center">You have searched for : {{query}}</p>
</div>
<div>
        {% for product in products %}
        <div>
            <div>
                <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div>
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
    <div class="row mx-auto">
        <p class="text-center">0 results found</p>
    </div>
        {% endfor %}
</div>
{% endblock %}

templates/signin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="signin-page account">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="block text-center">
            <a class="logo" href="{% url 'ecomapp:home' %}">
              <img src="{% static 'images/logo.png' %}" alt="">
            </a>
            <h2 class="text-center">Welcome Back</h2>
            <form class="text-left clearfix" action="#" >
              <div class="form-group">
                <input type="email" class="form-control"  placeholder="Email">
              </div>
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Password">
              </div>
              <div class="text-center">
                <button type="submit" class="btn btn-main text-center" >Login</button>
              </div>
            </form>
            <p class="mt-20">New in this site ?<a href="{% url 'ecomapp:signup' %}"> Create New Account</a></p>
            <p><a href="{% url 'ecomapp:forgot' %}"> Forgot your password?</a></p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="signin-page account">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="block text-center">
            <a class="logo" href="{% url 'ecomapp:home' %}">
              <img src="{% static 'images/logo.png' %}" alt="">
            </a>
            <h2 class="text-center">Create Your Account</h2>
            <form class="text-left clearfix" action="#">
              <div class="form-group">
                <input type="text" class="form-control"  placeholder="First Name">
              </div>
              <div class="form-group">
                <input type="text" class="form-control"  placeholder="Last Name">
              </div>
              <div class="form-group">
                <input type="text" class="form-control"  placeholder="Username">
              </div>
              <div class="form-group">
                <input type="email" class="form-control"  placeholder="Email">
              </div>
              <div class="form-group">
                <input type="password" class="form-control"  placeholder="Password">
              </div>
              <div class="text-center">
                <button type="submit" class="btn btn-main text-center">Sign In</button>
              </div>
            </form>
            <p class="mt-20">Already hava an account ?<a href="{% url 'ecomapp:signin' %}"> Login</a></p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}